main.go
pkg/utils/endpoint-url.go
test/utils/endpoint_test.go

Update the endpoint building function to allow for ports to be passed through the `--upload-api-root-url` option from the CLI.
Unit tests have also been updated.
Covered by CI
No impact on security
Manual release

upload-api-root-url cannot contain a port number

---

CHANGELOG.md
install.sh

Update the install script so that curl command doesn't fail when using older versions of curl.
Covered by CI/ Manual testing
No impact on security
Manual release

Unsupported Curl Option

---

main.go
pkg/upload/react-native-android.go

Add automatic detection and information parsing to the React Native Android functionality.
example:
`bugsnag-cli upload react-native-android --api-key=YOUR_API_KEY` 
output:
```
[INFO] /Users/josh.edney/repos/bugsnag-cli/test/testdata/react-native
[INFO] Locating Android manifest
[INFO] Setting app version from android/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
[INFO] Setting app version code from android/app/build/intermediates/merged_manifests/release/AndroidManifest.xml
[INFO] Uploading debug information for React Native Android
[SUCCESS] Upload(s) completed
```
- Default path to `./` if one isn't provided.
- Add flag for `app-manifest-path`. Defaults to `android/app/build/intermediates/merged_manifests/release/AndroidManifest.xml` if not set.
- Parse …

[PLAT-9893] React Native Android auto detection

---

main.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go

Remove the CLI option `--android-ndk-root` from the Android AAB upload section as it's not required due to the symbol files not needing to be passed through `objcopy`.
During testing, I also noticed that we're missing an `if err !=nil ` for checking if we need to fall back during the Android Proguard processing.
Remove `--android-ndk-root` from CLI options for Android AAB
Check if we have an `err` before we attempt to fall back to the default endpoint for Android Proguard
Covered By CI

Remove `--android-ndk-root` from Android AAB

---

pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go

Update the checking around the `AndroidManifest.xml` and only set it if the file exists.
Follows the pattern set out in the React Native Android section
Covered by CI and also manual testing.

Check if AndroidManifest.xml exists for Android Proguard, NDK and AAB

---

main.go
pkg/build/create.go
pkg/utils/get-repository-info.go
test/build/create_build_test.go

The `create-build` command previously assumes that the git repo it reads for source control parameters is the current directory (from which the command was executed). However I think it makes sense to allow a path to be passed in to the project and this used as the path for git.
Manually tested as existing tests don't cover this yet.

feat(create-build): add path option for project dir

---

pkg/utils/upload-options.go

#29 was incorrect for NDK - the version, version code and app ID are only cosmetic in the new NDK endpoint as we use a build ID in the .so file itself to uniquely identify the build. Therefore we don't need to error out if one of them is not present.

fix(upload-ndk): remove requirment for version info in NDK

---

.gitignore
install.js
package.json

The goal for this PR is to add the `install.js` script to handle the downloading and installing for the correct version of the Bugsnag CLI which will be published as a package to the NPM repository. I've currently got the package in the root of the repo as its only a small file and shouldn't really need anything else adding to it but we may want to move it to its own subfolder for ease of navigation.
Add scripts to the projects `package.json` 
- `bugsnagUpload` - `bugsnag-cli upload react-native-cli` - `npm run bugsnagUpload -- --api-key=YOUR_API_KEY`
- `bugsnagCreateBuild` - `bugsnag-cli create-build` - `npm run bugsnagCreateBuild -- --api-key=YOUR_API_KEY`
Add the foundation for the NPM package so that we can publish it via NPMJS and install the Bugsnag CLI via NPM
Tested locally using …

[PLAT-10142] Add NPM package to install Bugsnag CLI

---

CHANGELOG.md
main.go
pkg/android/manifest-reader-aab.go
pkg/build/create.go
pkg/proto_messages/Resources.pb.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/utils/upload-options.go
pkg/utils/validation.go

Move global flags:
- `appVersion` to `version`
- `appVersionCode` to `versionCode`
- `appBundleVersion` to `bundleVersion`
in the `create-build` and `upload dart` sub commands
Correct `buildUUID` name in server requests for Android Proguard
Get values from Android AAB manifest via resource ID
This approach matches the pattern used in all new sub commands.
- Android Proguard - Tested manually

[PLAT-10357] Move global `appVersion`, `appVersionCode` and `appBundleVersion` to sub commands

---

CHANGELOG.md
main.go
pkg/android/get-variant.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/react-native-android.go
pkg/utils/upload-options.go
pkg/utils/validation.go

Allow non-standard variants when not providing the bundle path as a flag to the CLI.
Correctly throw an error when trying to retrieve `apiKey`, `versionName` or `versionCode` from a non-existent android manifest file
Remove the hardcoded bundle path from the react native upload function and auto detect the variant from the folder structure.
Tested locally with multiple variants

[PLAT-10452] Remove hardcoded paths for react native bundle path

---

CHANGELOG.md
pkg/upload/react-native-android.go

Add support for the new bundle path used in React Native 0.72
Implement a switch statement to check the different paths used by React Native  versions for the bundle file.
This has been tested locally on RN version 0.69, 0.71 and 0.72

[PLAT-10546] Add bundle path support for React Native 0.72

---

CHANGELOG.md
package.json
pkg/upload/react-native-android.go

Ensure source map uploads for React Native Android versions lower than 0.70 can find and upload the correct `index.android.bundle` file.
Adjust `index.android.bundle` path checking for React Native Android to ensure that paths are tested in the correct order.
Test for `buildDirPath, "generated", "assets", "react"` before testing for `buildDirPath, "generated", "assets"`
Tested locally on React Native versions 0.60, 0.69 and 0.72

[HOTFIX] Add missing variant to the index.android.bundle path for react native android

---

CHANGELOG.md
install.js

Do not modify the projects `package.json` when installing the CLI via NPM.
Remove the `writeToPackageJson` from `install.js` so that we do not write to a projects `package.json` when installing via NPM.
Tested locally

remove adding commands to the package.json when installing via NPM

---

CHANGELOG.md
main.go
pkg/build/create.go
pkg/server/request.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/react-native-android.go

Validate but not upload source maps for all supported languages.
Add the `--dry-run` flag to all upload commands to process given source maps but not upload them. 
Removed the dry run log message from the `AAB` command to reduce the number of log messages
Tested manually, CI tests to be added during testing rework.

[PLAT-10654] Add --dry-run flag to upload commands

---

main.go
pkg/android/aab.go
pkg/build/create.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/react-native-android.go
pkg/upload/unity-android.go
pkg/utils/validation.go

Allow Unity Android symbols file uploads without needed an Android AAB file.
Example:
`bugsnag-cli upload unity-android --api-key=YOUR_API_KEY`
Output:
```
[INFO] No AAB files detected to process.
[INFO] Extracting Unity2022-1.0-v1-IL2CPP.symbols.zip into a temporary directory
[INFO] Uploading libil2cpp.so to https://upload.bugsnag.com:443/ndk-symbol
[SUCCESS] Uploaded libil2cpp.so
[INFO] Uploading libmain.so to https://upload.bugsnag.com:443/ndk-symbol
[SUCCESS] Uploaded libmain.so
[INFO] Uploading libunity.so to https://upload.bugsnag.com:443/ndk-symbol
[SUCCESS] Uploaded libunity.so
[INFO] Uploading libil2cpp.so to https://upload.bugsnag.com:443/ndk-symbol
[SUCCESS] Uploaded libil2cpp.so
[INFO] Uploading libmain.so to https://upload.bugsnag.com:443/ndk-symbol
[SUCCESS] Uploaded …
```

[PLAT-11067] Allow Unity Android symbol uploads without Android AAB file

---

install.sh
scripts/bump-version.sh

Bypass the rate limiting of the Github API when installing via the `install.sh` script and allow users to specify the version they wish to install via a command line flag.
Example:
`./install.sh --version=1.2.2`
Output:
```
==> This script will install:
/Users/josh.edney/.local/bugsnag/bin/bugsnag-cli
==> Downloading and installing Bugsnag CLI...
############################################## 100.0%
==> Installation successful!
```
Instead of using the github API to search for the latest release of the CLI we set the latest version using the `bump.sh` script within the `install.sh` script. We have also added an option to allow users to specify the version they wish to install using a `--version=x.x.x` flag
Tested locally but we could add this to the CI run if we wanted. Currently the CLI …

[PLAT-10966] Install script version handling

---

CHANGELOG.md
main.go
pkg/upload/dart.go

Ensure that the paths that are passed to the Dart upload option exist before attempting to use them.
Example error message when file doesn't exist:
`bugsnag-cli: error: --ios-app-path: stat /path/to/no/where: no such file or directory`
Use the `utils.Path` type for the `--ios-app-path` CLI option to validate whether the file exists or not.
Covered by CI

[PLAT-11305] Validate paths when passed to the Dart upload option

---

CHANGELOG.md
pkg/android/process-uploads.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/dart.go

Ensure that we properly handle failures with multiple file uploads for Android NDK and AAB when passing the `--fail-on-upload-error` CLI flag.
Rather than process each NDK file separately when dealing with an AAB file, we will pass an array of strings so that it can process them as one group enabling us to utilise the `--fail-on-upload-error` flag correctly. 
Adjust how we check if we're dealing with multiple files when checking for `failOnUploadError` to ensure that we still error if we're dealing with a single file.
Covered by CI

[PLAT-11330] Adjust how we handle multiple file uploads and failures for Android NDK/AAB

---

CHANGELOG.md
main.go
pkg/android/process-uploads.go
pkg/build/process-create-build.go
pkg/options/options.go
pkg/server/request.go
pkg/upload/all.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go

Ensure that when using the `--retries` argument on the CLI that if the upload fails the upload is retried the number of times equal to the value passed to the CLI argument. 
Add a new function to house and process the retry logic for sending requests to the upload endpoint.
Covered by CI

[HOTFIX] Ensure `--retries` is handled correctly during uploads

---

Gemfile
features/react-native-ios/rn0_69.feature
features/react-native-ios/rn0_70.feature
features/react-native-ios/rn0_72.feature
features/steps/steps.rb
makefile
pkg/ios/xcodebuild-utils.go
pkg/upload/react-native-ios.go

Ensure that we are able to find the bundle map and Info.plist file when working with archive over a regular build. This due to the required files being stored in a separate location than what we where previously checking.
e.g.
`/Users/administrator/Library/Developer/Xcode/DerivedData/rn0_69-fuannaoexgewdsfmbpxkkalrdlgw/Build/Products/Release-iphoneos/rn0_69.app/Info.plist`
vs
`/Users/administrator/Library/Developer/Xcode/DerivedData/rn0_69-fuannaoexgewdsfmbpxkkalrdlgw/Build/Intermediates.noindex/ArchiveIntermediates/rn0_69/BuildProductsPath/Release-iphoneos/rn0_69.app/Info.plist`
And 
`/Users/administrator/Library/Developer/Xcode/DerivedData/rn0_69-fuannaoexgewdsfmbpxkkalrdlgw/Build/Products/Release-iphoneos/main.jsbundle` 
vs
`/Users/administrator/Library/Developer/Xcode/DerivedData/rn0_6 …

[PLAT-11399] Update paths used when checking for react native ios bundle maps and Info.plist files

---

pkg/ios/dsym-utils.go
pkg/upload/dsym.go
pkg/upload/react-native-ios.go

- Add fallback endpoint for DSYM uploads when processing the DSYM API request.
Following the design for Android Proguard, we're going to attempt to send the request to the `\dsym` endpoint. However, if that returns a 404, we will attempt to send the request to the fallback URL.
Covered by CI

[PLAT-11638] Add fallback endpoint for DSYM uploads

---

features/dsym/expected_err_and_warn_scenarios.feature
features/steps/steps.rb
main.go
pkg/ios/dsym-utils.go
pkg/upload/dsym.go

Ensure that when handling zero size or missing dSYM files our standard behaviour is to exit with an error. 
Covered by CI

[PLAT-11631] Zero file behaviour for dSYM

---

CHANGELOG.md
features/dsym/expected_err_and_warn_scenarios.feature
main.go
pkg/android/process-uploads.go
pkg/server/request.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/dsym.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go

Deprecate the `--fail-on-upload-error` flag and log a warning if the flag is used. From now on when an upload fails it will always fail unless the API server returns a `409` error where it will instead log a warning informing the end user  that the duplicate file has been skipped.
I have also updated the formatting of some of the longer functions to fall inline with recent styling changes to make them easier to read.
Covered by CI

[PLAT-11746] Deprecate `--fail-on-upload-error` and handling for duplicate file response

---

CHANGELOG.md
supported-platforms.yml

@goblinbr raised [an issue](https://github.com/bugsnag/bugsnag-cli/issues/93) that highlighted the need for including `Windows_NT` in our supported platforms config file. 
Their original fix can be viewed [here](https://github.com/bugsnag/bugsnag-cli/pull/94) which includes 32 and 64 bit definitions identically defined as our pre-existing `Windows` definitions.

[PLAT-11977] Include Windows_NT in supported-platforms.yml

---

main.go
pkg/android/aab.go
pkg/android/build-objcopy-path.go
pkg/android/dex-build-id.go
pkg/android/get-android-info.go
pkg/android/get-ndk-root.go
pkg/android/get-variant.go
pkg/android/manifest-reader-xml.go
pkg/android/process-uploads.go
pkg/build/process-create-build.go
pkg/ios/dsym-utils.go
pkg/ios/xcodebuild-utils.go
pkg/log/logging.go
pkg/server/request.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/dsym.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go
pkg/utils/files.go
pkg/utils/get-repository-info.go
pkg/utils/gzip.go
pkg/utils/unzip.go

- Using fmt to concatenate strings throughout codebase for consistency
- I left any instances of filepath.Join as they were as I wasn't sure, but I can change these to use fmt if the reviewer thinks so?
- I only used fmt.Sprintf in log messages that needed to be concatenated. I can change this to use fmt.Sprintf in all log messages if the reviewer think so

Using fmt to concatenate strings throughout codebase for consistency

---

CHANGELOG.md
features/cli/bugsnag-cli.feature
features/steps/steps.rb
install.sh
main.go
package.json
pkg/log/logrus-wrapper.go
pkg/log/main.go
pkg/options/options.go
pkg/utils/validation.go

Add the ability to change the `logLevel` via the `--log-level` command line option.
Add validation to the setting of the log level to ensure that only accepted values are passed.
example:
```
$ bugsnag-cli upload react-native-android ... --log-level=fatal
```
Output:
```
[FATAL] failed after 1 attempts. 401 Unauthorized: invalid apiKey
```
Covered by CI

[PLAT-12131] Add the ability to set the log level 

---

.gitignore

To exclude unnecessary files included in `XCBuildData` when pushing new or modifying existing Xcode test fixtures.
One liner added into our `.gitignore`
N/A

[PLAT-12221] Ensure content of XCBuildData is never committed to bugsnag-cli

---

package.json

Ensure that the binary for the bugsnag-cli is correctly installed when using `pnpm` and `yarn` 
Add the `bin` directive to the `package.json` 
Tested locally.

[PLAT-12319] Ensure that the binary is installed when using `pnpm`  and `yarn`

---

CHANGELOG.md
main.go
pkg/options/options.go

Dont show `--upload-api-root-url` and `--build-api-root-url` flags in the general help output
Move the `UploadAPIRootUrl` and `BuildApiRootUrl` to their respective structs to ensure that these options are not displayed under the general help output but only when you specify `--help` for upload or create-build.
Covered by CI

[PLAT-12424] Dont show `--upload-api-root-url` and `--build-api-root-url` flags in the general help output

---

CHANGELOG.md
pkg/upload/android-aab.go

Ensure that extracted `.aab` files can be processed by the Android AAB upload function
Check to see if the path that has been given to the `ProcessAndroidAab` function contains folders that indicate it is an extracted `aab` file so that we can skip looking for an `aab` file within the provided folder.
Covered by CI

[PLAT-12453]  Ensure that extracted `.aab` files can be processed by the Android AAB upload function

---

README.md

Add the README documentation for the js command. The URL is currently broken but will be added by https://github.com/bugsnag/docs.bugsnag.com/pull/2333.

Document js upload

---

features/base-fixtures/rn0_69/package.json
features/base-fixtures/rn0_69/yarn.lock
features/base-fixtures/rn0_70/package.json
features/base-fixtures/rn0_70/yarn.lock
features/base-fixtures/rn0_72/package.json
features/base-fixtures/rn0_72/yarn.lock

Fix the dependabot warning https://github.com/bugsnag/bugsnag-cli/security/dependabot/20.
I upgraded the jest versions in the base fixture. I also had to update the babel-jest to match that version.
I changed the react and react native versions to be specified using `^` for consistency and so we test the latest patch.

Upgrade ReactNative fixtures dependencies

---

CHANGELOG.md
pkg/ios/dsym-utils.go
pkg/ios/xcodebuild-utils.go

Allow dSYM files with spaces in the name to be uploaded.
- Don't strip spaces from the Xcode build info
- Accept dSYM info length if its GT or EQ to 4 
Covered by CI

[PLAT-12623] Allow spaces when uploading dSYM

---

features/base-fixtures/rn0_69/yarn.lock

Update the yarn.lock file to fix CVE-2024-4068
Covered by CI

[PLAT-12295] Fix CVE-2024-4068 in the RN 0.69 test fixture

---

CHANGELOG.md
bin/bugsnag-cli
install.js
package.json

Allow execution when running `yarn bugsnag-cli`  and `npx @bugsnag/cli`
Install the bugsnag-cli binary into the package directory so that the package manager can create a symlink to the `node_modules/.bin` folder
Covered by CI

[PLAT-12862] Adjust the NPM package to allow execution from YARN 

---

CHANGELOG.md
install.js
package.json

Replace the use of the `axios` npm package to reduce the size of the package and the dependency on a 3rd party packages. As we no longer support nodejs 14 and lower we can use the built in `fetch` method.
Covered by CI

Replace `axios` with NPMs built in `fetch`

---

CHANGELOG.md
features/dsym/dsym_upload.feature
pkg/upload/dsym.go

Adjust the logging and handling around `--project-root` for dSYM uploads
Covered by CI

[PLAT-12916] Adjust logging and handling around `--project-root` for dSYM uploads

---

CHANGELOG.md
pkg/upload/android-ndk.go

Update the file check within the `upload android-ndk` command to check for any `.so*` files after it has checked for `.so.sym` files. This is to allow for additional file types introduced by Unity 6.
This has been tested locally but we should update the Unity tests to account for this.

[PLAT-13424] Check for .so.* files aswell as .so files when processing NDK source maps

---

CHANGELOG.md
pkg/upload/android-aab.go

Add some extra logging to the Android AAB upload process to show what paths are used when trying to upload .so files and proguard mappings
Covered by CI

[PLAT-13408] Android AAB extra debug logging

---

.buildkite/pipeline.yml
CHANGELOG.md
bugsnag-cli-install.js
config/.gitignore
docker-compose.yml
dockerfiles/Dockerfile.audit
features/cli/create-build.feature
install.sh
main.go
package.json
scripts/license_finder.sh

Due to the old license used for the `js-yaml` package, to comply with the License Audit we've updated to use the `yaml` node package
I have also added the license auditor step to the CI to ensure all packages comply.
Covered by CI

[PLAT-13456] Change the `js-yaml` node package to the `yaml` package 

---

CHANGELOG.md
features/Unity-Android/unity.feature
features/steps/steps.rb
install.sh
main.go
package.json
pkg/android/get-ndk-version.go

Ensure that we get the Android NDK version from a reliable source.
Get the `Pkg.Revision` from the NDK `source.properties` file
Covered by CI

[PLAT-13629] Get NDK version from the properties file

---

features/react-native/scripts/generate.js
features/steps/steps.rb
features/xcode/dsym.feature
features/xcode/xcode-archive.feature
features/xcode/xcode-build.feature
main.go
makefile
pkg/ios/xcarchive.go
pkg/options/options.go
pkg/upload/dsym.go
pkg/upload/react-native-ios.go
pkg/upload/react-native.go
pkg/upload/xcarhive.go
pkg/upload/xcode-archive.go
pkg/upload/xcode-build.go

Update the dSYM command to check for an Xcode archive first and then for a build in a given directory. 
Example:
`bugsnag-cli upload dsym /path/to/xcode/project`
Output for a build
```
[INFO] Searching for dSYM files to upload
[INFO] Searching for xcarchives in /path/to/xcode/project
[INFO] Setting `--project-root` from Xcode project settings: /path/to/xcode/project
[INFO] No dSYM files found in the xcarchive, searching in the build directory
[INFO] Setting `--project-root` from Xcode project settings: /path/to/xcode/project
[INFO] Uploading 6973FCB0-13E7-3627-A415-82B0EDCCC08F to http://localhost:9339/dsym
[INFO] Uploaded 6973FCB0-13E7-3627-A415-82B0EDCCC08F
[INFO] dSYM files successfully uploaded from the build directory
```
Output for an archive
```
[INFO] Searching for dSYM files to …
```

[PLAT-13836] dSYM Super Command

---

CHANGELOG.md
features/js/js-webpack4.feature
features/js/js-webpack5.feature
pkg/upload/js.go

Currently, we set the `--project-root` for the `upload js` command based on the directory where the `bugsnag-cli` command is run. This is fine unless you're running it from a directory outside your project. 
Instead, we want to break up the path given to the command and work out what to set the `--project-root` to based on where it can find a relative project file.
For example:
```
/User/Downloads/bugsnag-cli upload js /Path/To/Project
```
Will set the `--project-root` to `/Path/To/Project` rather than `/User/Downloads`
And:
```
/User/Downloads/bugsnag-cli upload js /Path/To/Project/Build/Folder
```
Will set the `--project-root` to `/Path/To/Project` rather than `/User/Downloads` as this is where it would find a relative project file (e.g. package.json/lerna.json/yarn.lock)
I've updated a …

[HOTFIX] Update how the `--project-root` is set for the `upload js` command

---

CHANGELOG.md
pkg/upload/js.go

Remove the `Path` package and replace it with the `filepath` package for consistency throughout the repo.
Currently, If the `sourcePath` is an absolute path we attempt to join it with the  `projectRoot`. This would sometimes result in an incorrect path and we'd be unable to read the source file.
Instead, we should find the `sourcePath` relative to the `sourceMapPath` if the `sourcePath` is an absolute path.
Covered by CI

[HOTFIX] Find source path relative to the sourcemap path

---

CHANGELOG.md
UPGRADING.md
main.go
pkg/options/options.go

Remove the deprecated `--fail-on-upload-error` option from the CLI
Covered by CI

Remove `--fail-on-upload-error`

---

README.md
UPGRADING.md
pkg/upload/react-native.go

Update the README to match the changes in the proposed docs. 
Update the `upload react-native` command to use the `upload dsym` command instead of the `upload xcode-build` command.
Covered by CI

README update & Update the react native command to use the dsym command

---

.buildkite/pipeline.yml
CHANGELOG.md
install.sh
main.go
package.json
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go

Update the reference for `--bundle-path` to `--bundle` for the `upload react-native-ios` and `upload react-native-android` commands
Covered by CI

[PLAT-14077] Fix typo in error messages

---

.buildkite/pipeline.yml
CHANGELOG.md
js/package.json
pkg/android/process-uploads.go
pkg/options/options.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/breakpad.go
pkg/upload/dart.go
pkg/upload/js.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go

Remove the `--overwrite` option from the dSYM related commands as this option is not used by the API
Covered by CI

Remove `--overwrite` from the upload dsym commands

---

Gemfile
features/steps/steps.rb
features/unity/android.feature

Update the Unity Android E2E tests to ensure we can test the sourcemaps and line mapping files uploaded to the mock API
Covered by CI

Fix Unity Android CI Flakes

---

README.md

Removes a trailing backtick in the NPM install code snippet in README.md.
Raised in: https://github.com/bugsnag/bugsnag-cli/pull/236

Fix NPM install code typo in README.md
