bugsnag/bugsnag-cli

CHANGELOG.md
CONTRIBUTING.md
README.md

Update docs for consistency with other repos and online docs.

docs: pre-launch tweaks to repo docs

---

README.md
main.go
pkg/build/create.go
pkg/upload/all.go
pkg/upload/dart.go
pkg/utils/validation.go
test/utils/endpoint_test.go

Add the command structure for the create build command options.
Add package and command structure for the build tool.
Covered by CI

[PLAT-9287] Add build tool command structure

---

main.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go

Add the scaffolding the for the Android command line options based off of the options from the ED
Add command line options for Android NDK, AAB and Proguard mapping files.
Covered By CI

[PLAT-9226-9227-9228] Add Android mapping command line options

---

main.go
pkg/upload/react-native-android.go

Adjust the react native android processing to fall inline with patterns set out in the android processing.

Tweak React Native Android processing

---

README.md

Branding and content update for the readme

docs(readme): update for android and rn

---

.gitignore
CHANGELOG.md
README.md
install.js
install.sh
package.json
pkg/upload/react-native-android.go

Add small fixes to the NPM package found when publishing.

Add small fixes to the NPM package

---

CHANGELOG.md
UPGRADING.md

docs(upgrade guide): add v2.0 entry

---

CHANGELOG.md

- Remove deprecated (renamed) CLI options - `--version`, `--app-version`, `--app-version-code` and `--app-bundle-version`. [52](https://github.com/bugsnag/bugsnag-cli/pull/52)
See [Upgrading Guide](./UPGRADING.md) for full details.
- Add support for Unity Android symbol files. [56](https://github.com/bugsnag/bugsnag-cli/pull/56)
- Add `--version` flag to the command to retrieve the version of the installed CLI. [51](https://github.com/bugsnag/bugsnag-cli/pull/51)
- Add `--dry-run` flag to all upload commands to validate but not upload source maps. [54](https://github.com/bugsnag/bugsnag-cli/pull/54)
- Automatically generate a unique value for the `buildUUID` parameter from `.aab` files when not specified in the `AndroidManifest` or `--build-uuid` option. …

v2.0.0 Release

---

pkg/ios/xcodebuild-utils.go

The getXcodeSchemes and getXcodeBuildSettings functions currently take a workspacePath argument which can be replaced by a path instead to make them a bit more flexible so they can be used to check if a workspace directory is passed, apply -workspace flag, if a project directory is passed then apply -project flag. Either path is empty, then just run xcodebuild without either flag as you would when running in the root of an xcode project.
To partially set things up for the new <path> behaviour. As explained in my design [here](https://smartbear.atlassian.net/wiki/spaces/EN/pages/3891986527/PLAT-11454+ED+-+iOS+dSYM+uploads+BugSnag+CLI#New-%3Cpath%3E-behaviour-explained).
The getXcodeSchemes and getXcodeBuildSettings functions
N/A - I'll test everything with MazeRunner at the end in the main …

[PLAT-11493] xcodebuild utility function updates

---

pkg/ios/xcodebuild-utils.go
pkg/server/request.go
pkg/upload/react-native-ios.go

Adjust how we handle looking up xcode project files for react native iOS to match, as closely as possible, the dSYM integration.
Adjust how the retry logic works so that it doesn't log a retrying message for when there is no retries.
Covered by CI

[PLAT-11669] Backport how we handle Xcode projects to React Native

---

CHANGELOG.md

Update the Changelog to include missing enhancements/fixes that where included in the release.

Update changelog for Release v2.3.0

---

main.go
pkg/options/options.go
pkg/upload/js.go

Add a new no-op command for uploading js sourcemaps.
New command added
Manual testing

Stub JS upload command

---

pkg/options/options.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/dsym.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go
pkg/utils/options.go

Amends the options text so they are standard across commands and alphabetically ordered.

docs: improved and standardised help text

---

main.go
pkg/android/process-uploads.go
pkg/build/process-create-build.go
pkg/options/options.go
pkg/server/request.go
pkg/upload/all.go
pkg/upload/android-aab.go
pkg/upload/android-ndk.go
pkg/upload/android-proguard.go
pkg/upload/dart.go
pkg/upload/dsym.go
pkg/upload/js.go
pkg/upload/react-native-android.go
pkg/upload/react-native-ios.go
pkg/upload/unity-android.go

Clean up some of the functions taking a large number of arguments by directly passing the struct.

Use option structs

---

.buildkite/pipeline.yml
.gitmodules
features/Unity-Android/unity-2023.feature
features/steps/steps.rb

Ensure that we have tests coverage for Unity Android
Covered by CI

[PLAT-12454] Add Unity Android Integration tests

---

package.json

Address SSRF vulnerability as mentioned in [this issue](https://github.com/bugsnag/bugsnag-cli/issues/131).
Version update in package.json.
A quick local run of the CLI `--help` command.

chore: bump axios to v1.7.4

---

.buildkite/pipeline.yml
features/steps/steps.rb
go.mod
makefile
pkg/android/find-merged-native-libs.go
pkg/server/request.go
pkg/upload/android-ndk.go
pkg/utils/get-repository-info.go
pkg/utils/gzip.go
pkg/utils/unzip.go
pkg/utils/upload-options.go
test/utils/files_test.go

Fix several flakes that have appeared within the CI system for this repo
Covered by CI

[FLAKES] Fix several flakes within the CI setup

---

features/base-fixtures/rn0_69/Gemfile
features/base-fixtures/rn0_70/Gemfile
features/base-fixtures/rn0_72/Gemfile
makefile

Use cocoapods version from react-native fixture rather than root
covered by CI

Fix CLI tests

---

CHANGELOG.md
install.sh
main.go
package.json
pkg/ios/xcodebuild-utils.go
pkg/options/options.go
pkg/upload/dsym.go
pkg/upload/react-native-ios.go
test/utils/dsym_test.go

- Add the `--configuration` option to the `upload dsym` command. [154](https://github.com/bugsnag/bugsnag-cli/pull/154)

v2.7.0 Release

---

features/xcode/dsym_upload.feature
features/xcode/xcarchive.feature
makefile

Add CI tests to cover the new `xcode-archive` command
Covered by CI

[PLAT-13238] Updates tests to cover the new Xcode Archive command

---

.github/workflows/downstream_updates.yml

Add github action to notify the unity repo on release

bump unity cli ref on release

---

CHANGELOG.md
scripts/bump-version.sh

Update the `CHANGELOG.md` format to match our other repos.
Update the version bump script to work with the new change log format.
Covered by CI

Update CHANGELOG.md format

---

CHANGELOG.md
bugsnag-cli-wrapper.d.ts
package.json

Add typescript definition to cli-wrapper to support typescript

Add type definition to cli wrapper

---

CHANGELOG.md
js/supported-platforms.yml
makefile

Add ARM Linux to the supported platforms for the NPM package.
Covered by CI and test the binary locally

Update the supported platforms for the CLI NPM packge

---

.buildkite/pipeline.yml
.buildkite/react-native/android.pipeline.yml
.buildkite/react-native/ios.pipeline.yml

Move to the macOS 15 CI queue
Bump the version of Unity we're using.
Covered by CI

Move CI to macOs 15

---

.buildkite/pipeline.yml
README.md

Add instructions on how to install the CLI via `brew`
Covered by CI

Add Homebrew installation instructions
